apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-zarf
  labels:
    zarf.dev/agent: ignore
spec:
  package: ghcr.io/enel1221/provider-zarf:v0.0.19
  packagePullPolicy: Always
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: provider-zarf-runtime